### ISSUE TITLE
shows on all attached monitors

### ISSUE THREAD

**Issue by maxpowa** [chrstphrknwtn/epoch-flip-clock-screensaver#1]
I really like this screensaver but I'd prefer if it only showed on the center monitor since I run a three monitor setup. It looks kinda silly when it's the same on all three. Is this behavior possible?

**Comment by chrstphrknwtn** [comment]
@maxpowa I finally got around to doing this, see the [0.0.4 Release](https://github.com/chrstphrknwtn/epoch-flip-clock/releases/tag/0.0.4)

Your method for showing on a single display is there, plus an alternate single display option. 😄

**Comment by maxpowa** [comment]
Cool thank you!
