### ISSUE TITLE
Wake with keyboard

### ISSUE THREAD

**Issue by wincent** [chrstphrknwtn/epoch-flip-clock-screensaver#3]
For other screensavers, I can "wake" them with mouse or keyboard, but it seems that only the mouse can wake epoch-flip-clock. I worked around this with [this commit](https://github.com/wincent/epoch-flip-clock/commit/4c3c09ea40c142164a7726f9e23677177b4638ee). No idea if this is legit, though.

Can you see any harm to letting keyboard events through?

**Comment by chrstphrknwtn** [comment]
33c83e3 uses your fix, not sure if this is legit either, but works on my machine! 

0.0.3 release [here](https://github.com/chrstphrknwtn/epoch-flip-clock/releases/tag/0.0.3).
